### ISSUE TITLE
Incorrectly erroring with "Could not use PIP3 to install CDSAPI"

### ISSUE THREAD

**Issue by rpurser47** [mathworks/climatedatastore#10]
[zhiling liao](https://www.mathworks.com/matlabcentral/profile/authors/13112879) reported on File Exchange

>Hi Rob,
>Thanks for this great toolbox!
>I am using MATLAB R2021b and at first i just could not run the example normally, it kept reporting "Could not use PIP3 to install CDSAPI", which i have actually installed.
>Then i changed "if result ~= 0" in line 19 of the file "setupCDSAPIIfNeeded.m" to "if result ~= 1", it finally worked.
>I hope this helps.
>Cheers

Appears need to look at potential return codes from PIP3 -- may need to accept more values as success.

**Comment by rpurser47** [comment]
I think this is resolved.  If other people see this issue, please reopen this issue.

**Comment by Rafnuss** [comment]
See potential fix :
https://github.com/mathworks/climatedatastore/pull/22/commits/97078cf591afd1eec14e59924eb3f1da2713fbfc

only tested on macos
