### ISSUE TITLE
Unable to resolve the name 'cdsapi_Factory.getCdsapi'.

### ISSUE THREAD

**Issue by FlorinZai** [mathworks/climatedatastore#11]
Thank you for the toolbox it could be very useful for me.
I am having issues in running the example. I installed Python3.8 and it shows up in Matlab. The CDS API seems to be installed. Running Matlab 2022b

Unable to resolve the name 'cdsapi_Factory.getCdsapi'.

Error in climateDataStoreDownloadFuture (line 88)
            obj.CdsapiClient = cdsapi_Factory.getCdsapi(options);

Error in climateDataStoreDownload (line 50)
    f = climateDataStoreDownloadFuture(datasetName, datasetOptions,options);

**Comment by onomitra** [comment]
It doesn't look like "cdsapi_Factory" or the "util" folder is on path when the toolbox gets installed.

**Comment by rpurser47** [comment]
Yep – looks like the toolbox packaging step is not adding util and doc to the MATLAB path.
-Rob

**Comment by rpurser47** [comment]
@FlorinZai, please try out the latest release to see if that fixes the issue.  Thank you for reporting this!

**Comment by FlorinZai** [comment]
@rpurser47 Thanks! Now it works, but I still had to add the C:\Users\USERNAME folder path to find the .cdsapirc file with the API key.
Good job with developing this toolbox, very handy!

**Comment by rpurser47** [comment]
Just to make sure that I understand, you had to add the folder with the .cdsapirc to the MATLAB path?  Or the Windows path?

**Comment by FlorinZai** [comment]
@rpurser47 Adding it to windows path did nothing. Strangely I need to be located in C:\Users\USERNAME with Matlab for it to work. Turned out that adding it to path wasn't wnough.

This is the error:
Error using setupCDSAPIIfNeeded 
Cannot create a credential file (\Users\flory\.cdsapirc).  No such file or directory

**Comment by FlorinZai** [comment]
@rpurser47 done. Thanks!
