### ISSUE TITLE
Link to the dataset used in Read Me example is incorrect

### ISSUE THREAD

**Issue by onomitra** [mathworks/climatedatastore#12]
The current link to the dataset used in  Read Me example (https://cds.climate.copernicus.eu/cdsapp#!/home#!%2Fdataset%2Fsatellite-sea-ice-thickness) doesn't actually lead to the dataset used. It just goes to the home page. The correct link is: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-ice-thickness?tab=form

**Comment by rpurser47** [comment]
My intention was to point to the overview of the dataset, not the download/query page.  So, I'd disagree this is a bug.  Interested in your thoughts.

**Comment by onomitra** [comment]
Looking at it more carefully, I agree with you. It is more appropriate to point to the home page in the "Usage" section. The "Example" section does point to the right page. I think my confusion was when I followed the link in the "Usage" section and did not immediately find a "download data" tab there as step 3 suggests.
