### ISSUE TITLE
ToolboxPackaging.prj mistakenly reports requirements on tests

### ISSUE THREAD

**Issue by michellehirsch** [mathworks/climatedatastore#14]
Todo: Rerun "Analyze toolbox" in the ToolboxPackaging.prj file. 

Currently, there is a warning under Requirements that files outside the toolbox folder are required (a couple of tests). If you rerun analysis, this will go away.

**Comment by rpurser47** [comment]
Fun issue.  I use [unit test mocks](https://microsoft.github.io/code-with-engineering-playbook/automated-testing/unit-testing/mocking/) to test the toolbox without sending hundreds of requests to Copernicus.  The dependency analysis was picking up that infrastructure, which is not part of the toolbox.  Removed the direct dependency to hide the mocking system from the code analyzer.
