### ISSUE TITLE
Data download runs till it crashes

### ISSUE THREAD

**Issue by parkercoye** [mathworks/climatedatastore#2]
Hey! This toolbox looks amazing, and is exactly what I'm looking for! I'm having trouble pulling data from it, though. 

I have the demo working fine - it pulls info with the API and plots it (ice thickness, I believe), but when I go to pull the data I actually want to look at, it runs but doesn't fetch any data and will go until I have to force quit MATLAB (I've waited for over an hour before quitting, and I'm only trying to pull 1 data point). 

Any pointers on this would be greatly appreciated! This is the code I am using to pull from the era5 land monthly means: 

datasetName ="reanalysis-era5-land-monthly-means";

options.product_type = 'monthly_averaged_reanalysis';
options.variable = 'surface_pressure';
options.format = 'grib';
options.year = '2021'; 
options.month = '01';
options.time = '00:00';

[downloadedFilePaths,citation] = climateDataStoreDownload('reanalysis-era5-land-monthly-means',options);

I've tried using this code as well, and it performs the same way (goes until I have to force quit)

datasetName ="reanalysis-era5-pressure-levels";
options.product_type = "reanalysis";
options.format = "grib";
options.year = "2020";
options.month = "01";
options.day = "01";
options.pressure_level = "1";
options.variable = "divergence";
options.time = "06:00";
[downloadedFilePaths,citation] = climateDataStoreDownload(datasetName,options);

**Comment by rpurser47** [comment]
OK, I've finally solved this problem.  I did a major rewrite, and I should release a new version tomorrow.  Note that many of these requests can take a long time to process -- I've had it take 25 minutes!  You can check on the status of your request by visiting [the CDS request status page](https://cds.climate.copernicus.eu/cdsapp#!/yourrequests).  I added a test that reproduces your case (and it works now).

**Comment by rpurser47** [comment]
release 2.0 is done.  Let me know how it works for you!

**Comment by parkercoye** [comment]
It works great - thanks Rob!!
